### ISSUE TITLE
配置文件问题

### ISSUE THREAD

**Issue by L1ulee** [yuxuanchiadm/SkyCraftUpdater#11]
[Server thread][ERROR]: [SkyCraftUpdater] Could not load provider manifest
请问这个是什么问题，是在配置处的问题吗?

> 服务端核心:LoliServer-1.16.5-185-server.jar

配置文件如下:
```yaml
updater:
  enableProvider: true
  clientPath: client
  manifestPath: client_manifest.json
  listenIp: 0.0.0.0
  listenPort: 12182
  requireUpdater: false
  kickMessage: 需要安装更新器在能进入服务器哦!
```
client目录结构如下:
```
-client
 ├─config
 ├─crash-reports
 ├─CustomSkinLoader
 ├─defaultconfigs
 ├─kubejs
 ├─local
 ├─logs
 ├─mods
 ├─natives
 ├─openloader
 ├─paintings
 ├─patchouli_books
 ├─resourcepacks
 ├─saves
 ├─schematics
 ├─screenshots
 ├─shaderpacks
 └─worldshape
```
